#!/bin/bash
echo "=== Xcode Project Setup Instructions ==="
echo ""
echo "1. Open Xcode"
echo "2. File → New → Project"
echo "3. Select 'iOS' tab → 'App' → Next"
echo "4. Fill in:"
echo "   - Product Name: IppoMVP"
echo "   - Team: None (for simulator, this is fine)"
echo "   - Organization Identifier: com.cruce"
echo "   - Interface: SwiftUI"
echo "   - Language: Swift"
echo "   - Uncheck 'Include Tests'"
echo "5. Save to: /Users/crucegauntlet/Desktop/Ippo MVP/"
echo ""
echo "After creating, you'll add the Watch app target and import files."
